name: ssh

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: tips
        run: |
          echo "touch /tmp/keepalive"
          echo "https://tmate.io/t/"
          
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
        

